# Generated by Django 2.2.6 on 2019-11-21 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import project.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bank account', models.IntegerField(validators=[project.models.validate_positive])),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(blank=True, default='', help_text='Description', max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(default='static/images/default/defaut.png', upload_to='static/images')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tag', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RealEntity',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='project.Entity')),
                ('Phone number', models.IntegerField(null=True, validators=[project.models.validate_positive])),
            ],
            bases=('project.entity',),
        ),
        migrations.AddField(
            model_name='entity',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='Images', to='project.Image'),
        ),
        migrations.AddField(
            model_name='entity',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='Tags', to='project.Tag'),
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.BankAccount')),
            ],
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Buy Date', models.DateTimeField(auto_now_add=True)),
                ('Amount', models.IntegerField(validators=[project.models.validate_positive])),
                ('Buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Buyer')),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('realentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='project.RealEntity')),
                ('bank_accounts', models.ManyToManyField(through='project.Buyer', to='project.BankAccount')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('project.realentity',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='project.Entity')),
                ('Price per unit', models.FloatField(validators=[project.models.validate_positive])),
                ('Store Amount', models.IntegerField(validators=[project.models.validate_positive])),
                ('buy_product', models.ManyToManyField(through='project.Buy', to='project.Buyer')),
            ],
            bases=('project.entity',),
        ),
        migrations.AddField(
            model_name='buy',
            name='Selled Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Product'),
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('realentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='project.RealEntity')),
                ('Name', models.CharField(max_length=150)),
                ('Create Date', models.DateTimeField(auto_now_add=True)),
                ('Email', models.EmailField(max_length=254)),
                ('Bank account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.BankAccount')),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.MyUser')),
            ],
            bases=('project.realentity',),
        ),
        migrations.AddField(
            model_name='product',
            name='Store',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='project.Store'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='MyUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.MyUser'),
        ),
    ]
