# Generated by Django 2.2.6 on 2019-11-17 13:36

from django.db import migrations, models
import django.db.models.deletion
import project.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bank account', models.IntegerField(validators=[project.models.validate_positive])),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Description', models.CharField(max_length=400, null=True)),
                ('Create Date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='project.Entity')),
                ('Price per unit', models.FloatField(validators=[project.models.validate_positive])),
                ('Amount', models.IntegerField(validators=[project.models.validate_positive])),
            ],
            bases=('project.entity',),
        ),
        migrations.CreateModel(
            name='RealEntity',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='project.Entity')),
                ('Email', models.EmailField(max_length=254)),
                ('Phone number', models.IntegerField(null=True, validators=[project.models.validate_positive])),
            ],
            bases=('project.entity',),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('realentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='project.RealEntity')),
                ('hello', models.CharField(max_length=12)),
                ('User Bank Accounts', models.ManyToManyField(to='project.BankAccount')),
            ],
            bases=('project.realentity',),
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('realentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='project.RealEntity')),
                ('Bank account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.BankAccount')),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.User')),
            ],
            bases=('project.realentity',),
        ),
    ]
