# Generated by Django 2.2.6 on 2019-11-22 00:04

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import project.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bank account', models.IntegerField(validators=[project.models.validate_positive])),
            ],
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Buy Date', models.DateTimeField(auto_now_add=True)),
                ('Amount', models.IntegerField(validators=[project.models.validate_positive])),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.BankAccount')),
            ],
        ),
        migrations.CreateModel(
            name='BuyOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Buy Date', models.DateTimeField(auto_now_add=True)),
                ('Buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Buyer')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(default='static/images/default/defaut.png', upload_to='static/images')),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Description', models.CharField(blank=True, default='', help_text='Description', max_length=400)),
                ('Phone', models.IntegerField(blank=True, null=True, validators=[project.models.validate_positive])),
                ('Accounts', models.ManyToManyField(through='project.Buyer', to='project.BankAccount')),
                ('Images', models.ManyToManyField(blank=True, related_name='Images_User', to='project.Image')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.FloatField(validators=[project.models.validate_positive])),
                ('Offer name', models.CharField(max_length=50)),
                ('Offer description', models.CharField(max_length=150)),
                ('buy_offer', models.ManyToManyField(through='project.BuyOffer', to='project.Buyer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price per unit', models.FloatField(validators=[project.models.validate_positive])),
                ('Store Amount', models.IntegerField(validators=[project.models.validate_positive])),
                ('Visible', models.BooleanField(default=True)),
                ('Description', models.CharField(blank=True, default='', help_text='Description', max_length=400)),
                ('Images', models.ManyToManyField(blank=True, related_name='Images_Product', to='project.Image')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tag', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField(validators=[project.models.validate_positive])),
                ('Product offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Product')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Offer')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Create Date', models.DateTimeField(auto_now_add=True)),
                ('Email', models.EmailField(max_length=254)),
                ('Description', models.CharField(blank=True, default='', help_text='Description', max_length=400)),
                ('Phone', models.IntegerField(blank=True, null=True, validators=[project.models.validate_positive])),
                ('Bank account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.BankAccount')),
                ('Images', models.ManyToManyField(blank=True, related_name='Images_Store', to='project.Image')),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.MyUser')),
                ('Tags', models.ManyToManyField(blank=True, related_name='Tags_Store', to='project.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Store',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='project.Store'),
        ),
        migrations.AddField(
            model_name='product',
            name='Tags',
            field=models.ManyToManyField(blank=True, related_name='Tags_Product', to='project.Tag'),
        ),
        migrations.AddField(
            model_name='product',
            name='buy_product',
            field=models.ManyToManyField(through='project.Buy', to='project.Buyer'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='Tags',
            field=models.ManyToManyField(blank=True, related_name='Tags_User', to='project.Tag'),
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Message', models.CharField(max_length=1000)),
                ('type', models.CharField(choices=[('N', 'Normal'), ('I', 'Important'), ('W', 'Warning')], default='N', max_length=15)),
                ('reciever_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever_table', to='project.MyUser')),
                ('sender_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_table', to='project.MyUser')),
            ],
        ),
        migrations.AddField(
            model_name='buyoffer',
            name='Offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Offer'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='MyUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.MyUser'),
        ),
        migrations.AddField(
            model_name='buy',
            name='Buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Buyer'),
        ),
        migrations.AddField(
            model_name='buy',
            name='Selled Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Product'),
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Initial Date', models.DateTimeField()),
                ('Duration(sec)', models.IntegerField(validators=[project.models.validate_positive])),
                ('Money', models.IntegerField(validators=[project.models.validate_positive])),
                ('Offered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Offer')),
                ('Winner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Buyer')),
            ],
        ),
    ]
