# Generated by Django 2.2.6 on 2019-11-17 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hello',
        ),
    ]
