# Generated by Django 2.2.6 on 2019-11-22 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='Accounts',
            field=models.ManyToManyField(blank=True, through='project.Buyer', to='project.BankAccount'),
        ),
    ]
