# Generated by Django 2.2.6 on 2019-11-21 02:47

from django.db import migrations, models
import django.db.models.deletion
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Buy Date', models.DateTimeField(auto_now_add=True)),
                ('Buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Buyer')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.FloatField(validators=[project.models.validate_positive])),
                ('Offer name', models.CharField(max_length=50)),
                ('Offer description', models.CharField(max_length=150)),
                ('buy_offer', models.ManyToManyField(through='project.BuyOffer', to='project.Buyer')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Visible',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='SubOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField(validators=[project.models.validate_positive])),
                ('Product offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Product')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Offer')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Message', models.CharField(max_length=1000)),
                ('type', models.CharField(choices=[('N', 'Normal'), ('I', 'Important'), ('W', 'Warning')], default='N', max_length=15)),
                ('reciever_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever_table', to='project.MyUser')),
                ('sender_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_table', to='project.MyUser')),
            ],
        ),
        migrations.AddField(
            model_name='buyoffer',
            name='Offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Offer'),
        ),
        migrations.AddField(
            model_name='buyoffer',
            name='Product offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Product'),
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Initial Date', models.DateTimeField()),
                ('Duration(sec)', models.IntegerField(validators=[project.models.validate_positive])),
                ('Money', models.IntegerField(validators=[project.models.validate_positive])),
                ('Offered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Offer')),
                ('Winner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.Buyer')),
            ],
        ),
    ]
