# Generated by Django 2.2.6 on 2019-11-21 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20191121_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='Winner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Buyer'),
        ),
    ]
