# Generated by Django 2.2.6 on 2019-11-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_user_hello'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='Description',
            field=models.CharField(default='', help_text='Description', max_length=400),
        ),
    ]
