# Generated by Django 2.2.6 on 2019-11-21 03:00

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20191121_0256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyoffer',
            name='Product offer',
        ),
        migrations.AlterField(
            model_name='realentity',
            name='Phone number',
            field=models.IntegerField(blank=True, null=True, validators=[project.models.validate_positive]),
        ),
        migrations.AlterField(
            model_name='tag',
            name='Tag',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
