# Generated by Django 2.2.6 on 2019-11-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20191122_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Price_per_unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Visible',
        ),
        migrations.RemoveField(
            model_name='product',
            name='buy_product',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='Accounts',
            field=models.ManyToManyField(blank=True, related_name='Accounts_User', through='project.Buyer', to='project.BankAccount'),
        ),
        migrations.DeleteModel(
            name='Buy',
        ),
    ]
