# Generated by Django 2.2.6 on 2019-11-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20191117_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='Description',
            field=models.CharField(blank=True, default='', help_text='Description', max_length=400),
        ),
    ]
