# Generated by Django 2.2.6 on 2019-11-25 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20191125_2242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suboffer',
            old_name='Product offer',
            new_name='Product_offer',
        ),
        migrations.AddField(
            model_name='offer',
            name='Store',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='project.Store'),
        ),
    ]
