# Generated by Django 2.2.6 on 2019-11-17 16:28

from django.db import migrations, models
import django.db.models.deletion
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20191117_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(default='static/images/default/defaut.png', height_field=200, max_length=200, upload_to='static/images', width_field=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tag', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Amount',
            new_name='Store Amount',
        ),
        migrations.RemoveField(
            model_name='user',
            name='User Bank Accounts',
        ),
        migrations.AddField(
            model_name='product',
            name='Store',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='project.Store'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='Create Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.BankAccount')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.User')),
            ],
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Buy Date', models.DateTimeField(auto_now_add=True)),
                ('Amount', models.IntegerField(validators=[project.models.validate_positive])),
                ('Buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Buyer')),
                ('Selled Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='buy_product',
            field=models.ManyToManyField(through='project.Buy', to='project.Buyer'),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_accounts',
            field=models.ManyToManyField(through='project.Buyer', to='project.BankAccount'),
        ),
    ]
