# Generated by Django 2.2.6 on 2019-11-21 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20191121_0300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realentity',
            old_name='Phone number',
            new_name='Phone',
        ),
    ]
