# Generated by Django 2.2.6 on 2019-11-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20191117_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='images',
            field=models.ManyToManyField(related_name='Images', to='project.Image'),
        ),
        migrations.AddField(
            model_name='entity',
            name='tags',
            field=models.ManyToManyField(related_name='Tags', to='project.Tag'),
        ),
    ]
