# Generated by Django 2.2.6 on 2019-11-26 00:26

from django.db import migrations, models
import project.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20191125_2341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suboffer',
            old_name='offer',
            new_name='Offer',
        ),
        migrations.AddField(
            model_name='buyoffer',
            name='Amount',
            field=models.IntegerField(default=1, validators=[project.models.validate_positive]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='Images',
            field=models.ManyToManyField(blank=True, related_name='Images_Offer', to='project.Image'),
        ),
        migrations.AddField(
            model_name='offer',
            name='Tags',
            field=models.ManyToManyField(blank=True, related_name='Tags_Offer', to='project.Tag'),
        ),
    ]
