# Generated by Django 2.2.6 on 2019-11-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20191117_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='Images', to='project.Image'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='Tags', to='project.Tag'),
        ),
    ]
