# Generated by Django 2.2.6 on 2019-11-26 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20191126_0026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suboffer',
            old_name='Product_offer',
            new_name='product_offer',
        ),
    ]
