# Generated by Django 2.2.6 on 2019-11-26 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20191126_0050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suboffer',
            old_name='product_offer',
            new_name='Product_offer',
        ),
    ]
