# Generated by Django 2.2.6 on 2019-11-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20191117_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='Image',
            field=models.ImageField(default='static/images/default/defaut.png', upload_to='static/images'),
        ),
    ]
