# Generated by Django 2.2.6 on 2019-11-26 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20191126_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suboffer',
            name='Offer',
        ),
        migrations.AddField(
            model_name='offer',
            name='Suboffer',
            field=models.ManyToManyField(related_name='Suboffer_offer', to='project.SubOffer'),
        ),
    ]
