# Generated by Django 2.2 on 2020-02-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20191126_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='Name',
            field=models.CharField(default='default', max_length=200),
            preserve_default=False,
        ),
    ]
