# Generated by Django 2.2 on 2020-02-16 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20200216_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='Create Date',
        ),
    ]
