# Generated by Django 2.2 on 2020-02-16 17:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_remove_store_create date'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='Create_Date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
