# Generated by Django 2.2 on 2020-02-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_store_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='Image',
            field=models.ImageField(default='default.png', upload_to='images'),
        ),
    ]
