# Generated by Django 2.2 on 2020-03-10 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_auto_20200220_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.MyUser')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='Owner',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='project.MyUser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='Image',
            field=models.ImageField(default='default.jpg', upload_to='images'),
        ),
        migrations.CreateModel(
            name='ShoppingOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.PositiveIntegerField()),
                ('Cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.ShoppingCart')),
                ('Offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Offer')),
            ],
        ),
    ]
