# Generated by Django 2.2 on 2020-03-10 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_auto_20200310_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='Owner',
        ),
    ]
