# Generated by Django 2.2 on 2020-03-10 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_remove_image_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='Owner',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='project.MyUser'),
            preserve_default=False,
        ),
    ]
