# Generated by Django 2.2 on 2020-03-10 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_image_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='Owner',
        ),
    ]
