# Generated by Django 2.2 on 2020-03-10 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_remove_image_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='owner',
        ),
        migrations.AddField(
            model_name='myuser',
            name='cart',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.ShoppingCart'),
            preserve_default=False,
        ),
    ]
