# Generated by Django 2.2 on 2020-03-12 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_auto_20200310_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='Bank_account',
            new_name='Account',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='cart',
            new_name='Cart',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='Accounts',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='MyUser',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, to='project.MyUser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auction',
            name='Winner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.BankAccount'),
        ),
        migrations.AlterField(
            model_name='buyoffer',
            name='Buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.BankAccount'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='buy_offer',
            field=models.ManyToManyField(through='project.BuyOffer', to='project.BankAccount'),
        ),
        migrations.DeleteModel(
            name='Buyer',
        ),
    ]
