# Generated by Django 2.2 on 2020-03-12 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_auto_20200312_1632'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together={('MyUser', 'Account')},
        ),
    ]
