# Generated by Django 2.2 on 2020-03-18 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_auto_20200318_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='Owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='project.MyUser'),
            preserve_default=False,
        ),
    ]
