# Generated by Django 2.2 on 2020-03-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_image_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Store_Amount',
            field=models.PositiveIntegerField(),
        ),
    ]
