# Generated by Django 2.2 on 2020-03-27 21:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_auto_20200327_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='Duration_in_sec',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='ended',
        ),
        migrations.AddField(
            model_name='auction',
            name='Ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='auction',
            name='Final_Date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 27, 21, 40, 35, 96851, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
