# Generated by Django 3.0.4 on 2020-04-08 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0028_auction_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='reciever_user',
        ),
        migrations.AddField(
            model_name='chat',
            name='receiver_user',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_table', to='project.MyUser'),
            preserve_default=False,
        ),
    ]
