# Generated by Django 3.0.4 on 2020-10-29 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0030_auto_20200408_2353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='Name',
            new_name='ImageName',
        ),
    ]
