# Generated by Django 2.2 on 2020-03-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='Number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
